import React,{useState,useEffect} from 'react'
import { Card, FormField, Loader } from '../components'

const RenderPosts=({data,title})=>{
  if(data?.length>0){
    return (
      data.map((post)=>{
        return <Card key={post._id} {...post}/>
      })
    )
  }
  
  return (
    <h2 className="mt-5 font-bold uppercase text-[#bada55] text-xl">
      {title}
    </h2>
  )
}

const Home = () => {
  const [loading, setloading] = useState(false)
  const [allposts, setallposts] = useState(null)
  const [querytext, setquerytext] = useState('hello')
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-4xl">
          The Community Showcase
        </h1>
        <p className='md:text-lg font-medium text-[#bada55] text-md italic'>"Let the world see your creativity"</p>
        <p className="mt-2 text-[#666e75] text-sm max-w-[500px]">
          Browse through the collection of imaginative and visually stunning images generated by DALL-E AI Second Draft
        </p>

        <div className="mt-16">
          <FormField/>
        </div>

        <div className="mt-10">
          {loading?(
            <div className="flex justify-center items-center">
              <Loader/>
            </div>
          ):(
            <>
              {querytext && (
                <h2 className="font-medium text-[#666e75] mb-3 text-xl">
                  Showing results for <span className='text-[#bada55]'>{querytext}</span>
                </h2>
              )}
              <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
                {querytext?(
                  <RenderPosts
                    data={[]}
                    title="No search results found!"
                  />
                ):(
                  <RenderPosts
                    data={[]}
                    title="No posts found!"
                  />
                )}
              </div>
            </>
          )}
        </div>
      </div>
    </section>
  )
}

export default Home